### ISSUE TITLE
Some Errors...

### ISSUE THREAD

**Issue by lieanu** [zachriggle/pwndbg#15]
```
Traceback (most recent call last):
  File "/home/lieanu/tools/pwndbg/gdbinit.py", line 10, in <module>
    import pwndbg
  File "/home/lieanu/tools/pwndbg/pwndbg/__init__.py", line 5, in <module>
    import pwndbg.arguments
  File "/home/lieanu/tools/pwndbg/pwndbg/arguments.py", line 11, in <module>
    import pwndbg.disasm
  File "/home/lieanu/tools/pwndbg/pwndbg/disasm/__init__.py", line 11, in <module>
    import pwndbg.disasm.arch
  File "/home/lieanu/tools/pwndbg/pwndbg/disasm/arch.py", line 225, in <module>
    generic_assistant = DisassemblyAssistant(None)
  File "/home/lieanu/tools/pwndbg/pwndbg/disasm/arch.py", line 27, in __init__
    CS_OP_IMM: self.immediate,
NameError: name 'CS_OP_IMM' is not defined
```

```
Traceback (most recent call last):
  File "/home/lieanu/tools/pwndbg/pwndbg/events.py", line 77, in caller
    func()
  File "/home/lieanu/tools/pwndbg/pwndbg/vmmap.py", line 90, in explore_registers
    find(pwndbg.regs[regname])
  File "/home/lieanu/tools/pwndbg/pwndbg/memoize.py", line 43, in __call__
    value = self.func(*args, **kwargs)
  File "/home/lieanu/tools/pwndbg/pwndbg/regs.py", line 273, in __getitem__
    if isinstance(item, (int,long)):
NameError: name 'long' is not defined
Python Exception <class 'NameError'> name 'long' is not defined: 
```

**Comment by zachriggle** [comment]
What were you working on when this happened?  Was everything up-to-date (latest pwndbg, latest Capstone 4.0)?

The `CS_OP_IMM` error shouldn't happen, and I can't reproduce it.  I can easily make a reference to that symbol.

```diff
diff --git a/pwndbg/disasm/arch.py b/pwndbg/disasm/arch.py
index c1bc475..9f94a61 100644
--- a/pwndbg/disasm/arch.py
+++ b/pwndbg/disasm/arch.py
@@ -4,6 +4,8 @@ import capstone
 import collections
 from capstone import *
 
+CS_OP_IMM
+
 debug = False
 
 groups = {v:k for k,v in globals().items() if k.startswith('CS_GRP_')}
```

The `int`-vs-`long` should also not happen, as we add `long` to the global namespace in [`inthook.py`](https://github.com/zachriggle/pwndbg/blob/master/pwndbg/inthook.py).

**Comment by lieanu** [comment]
Sorry, it's a  false alarm, I updated `gdb` to version `7.10` in my laptop yesterday, it use `python 3.4`.
After rebuilding, it works now. :+1:
