### ISSUE TITLE
Python Exception <class 'AttributeError'> 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by P4N74** [zachriggle/pwndbg#18]
While running a program with `core` file in gdb, I'm getting an error saying `Python Exception <class 'AttributeError'> 'str' object has no attribute 'decode'` which is coming from the line
```
    if pwndbg.compat.python3:
        data = data.decode()
```
if file `vmmap.py`. I checked the type of data but it turned out to be `<class 'str'>`.  Also it gives error when I run `vmmap` inside the `gdb` session which was started with core file.
```
Python Exception <class 'AttributeError'> 'str' object has no attribute 'decode': 
Error occurred in Python command: 'str' object has no attribute 'decode'
Python Exception <class 'AttributeError'> 'str' object has no attribute 'decode':
```
On running `vmmap` while running a program without core file work fine.

**Comment by zachriggle** [comment]
If you don't mind, can you provide a full backtrace via:

```
sh$ gdb binary core
gdb$ pi
>>> pwndbg.commands.context.context()
>>> pwndbg.commands.vmmap.vmmap()
```

**Comment by P4N74** [comment]
Here is the backtrace you asked for: 

```
pwn> pi
>>> pwndbg.commands.context.context()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/panda/ctf-tools/pwndbg/pwndbg/commands/__init__.py", line 49, in __call__
    return self.function(*args, **kwargs)
  File "/home/panda/ctf-tools/pwndbg/pwndbg/commands/__init__.py", line 84, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/panda/ctf-tools/pwndbg/pwndbg/commands/context.py", line 35, in context
    if 'r' in args: result.extend(context_regs())
  File "/home/panda/ctf-tools/pwndbg/pwndbg/commands/context.py", line 50, in context_regs
    result.extend(get_regs())
  File "/home/panda/ctf-tools/pwndbg/pwndbg/commands/context.py", line 82, in get_regs
    result.append("%s%s %s" % (m, regname, pwndbg.chain.format(value)))
  File "/home/panda/ctf-tools/pwndbg/pwndbg/chain.py", line 45, in format
    enhanced = pwndbg.enhance.enhance(chain[-2], code=code)
  File "/home/panda/ctf-tools/pwndbg/pwndbg/enhance.py", line 65, in enhance
    page = pwndbg.vmmap.find(value)
  File "/home/panda/ctf-tools/pwndbg/pwndbg/memoize.py", line 43, in __call__
    value = self.func(*args, **kwargs)
  File "/home/panda/ctf-tools/pwndbg/pwndbg/vmmap.py", line 52, in find
    for page in get():
  File "/home/panda/ctf-tools/pwndbg/pwndbg/vmmap.py", line 30, in get
    pages.extend(proc_pid_maps())
  File "/home/panda/ctf-tools/pwndbg/pwndbg/memoize.py", line 43, in __call__
    value = self.func(*args, **kwargs)
  File "/home/panda/ctf-tools/pwndbg/pwndbg/vmmap.py", line 151, in proc_pid_maps
    data = data.decode()
AttributeError: 'str' object has no attribute 'decode'
>>> pwndbg.commands.vmmap.vmmap()
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/panda/ctf-tools/pwndbg/pwndbg/commands/__init__.py", line 49, in __call__
    return self.function(*args, **kwargs)
  File "/home/panda/ctf-tools/pwndbg/pwndbg/commands/__init__.py", line 84, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/panda/ctf-tools/pwndbg/pwndbg/commands/vmmap.py", line 28, in vmmap
    for page in pwndbg.vmmap.get():
  File "/home/panda/ctf-tools/pwndbg/pwndbg/vmmap.py", line 30, in get
    pages.extend(proc_pid_maps())
  File "/home/panda/ctf-tools/pwndbg/pwndbg/memoize.py", line 43, in __call__
    value = self.func(*args, **kwargs)
  File "/home/panda/ctf-tools/pwndbg/pwndbg/vmmap.py", line 151, in proc_pid_maps
    data = data.decode()
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by zachriggle** [comment]
What version of Python is GDB using?

**Comment by P4N74** [comment]
It's Python 3.4.3 

```
pwn> pi
>>> import sys
>>> sys.version
'3.4.3 (default, Oct 14 2015, 20:31:36) \n[GCC 4.8.4]'
>>> 
```

**Comment by zachriggle** [comment]
Fixed! Thanks for the bug report :)

**Comment by P4N74** [comment]
welcome :) BTW will you give some hint on how you pointed out the main source of error.
