### ISSUE TITLE
Crash under Python2

### ISSUE THREAD

**Issue by tmfink** [zachriggle/pwndbg#28]
When running pwndbg with a GDB that uses python2, you get the following crash:

~~~
$ gdb /bin/ls
GNU gdb (GDB) 7.8.2
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "/pwndbg/gdbinit.py", line 10, in <module>
    import pwndbg
  File "/pwndbg/pwndbg/__init__.py", line 6, in <module>
    import pwndbg.arguments
  File "/pwndbg/pwndbg/arguments.py", line 11, in <module>
    import pwndbg.disasm
  File "/pwndbg/pwndbg/disasm/__init__.py", line 17, in <module>
    import pwndbg.emu.emulator
  File "/pwndbg/pwndbg/emu/__init__.py", line 2, in <module>
    import pwndbg.emu.x86
  File "/pwndbg/pwndbg/emu/x86.py", line 2, in <module>
    import pwndbg.emu.emulator
  File "/pwndbg/pwndbg/emu/emulator.py", line 49
    if DEBUG: print(*a, **kw)
                    ^
SyntaxError: invalid syntax
Reading symbols from /bin/ls...(no debugging symbols found)...done.
(gdb) python import sys; print(sys.version)
2.7.6 (default, Jun 22 2015, 18:01:27) 
[GCC 4.8.2]
~~~

This is because in Python2, `print` is a statement, not a function. 

This _could_ be fixed by adding `from __future__ import print_function` at the top of `emulator.py`. However, I noticed that print is used often in the repo. 

To provide co-compatibility to python2/3, you should add the following at the beginning of the imports of each `*.py` file:
~~~
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
~~~

I wasn't sure how you wanted to handle the co-compatibility, so I decided to make this issue instead of a pull request.

**Comment by zachriggle** [comment]
Fixed with d13b9e85ce91d1ac294a01f51106edaafaa9db9b
