### ISSUE TITLE
broken on ubuntu vivid

### ISSUE THREAD

**Issue by crowell** [zachriggle/pwndbg#7]
```
minishwoods ~/pwndbg ‹master*› » gdb /bin/ls
GNU gdb (Ubuntu 7.9-1ubuntu1) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "~/pwndbg/gdbinit.py", line 10, in <module>
    import pwndbg
  File "/home/jeff/pwndbg/pwndbg/__init__.py", line 102
    print pwndbg.color.red(msg)
               ^
SyntaxError: invalid syntax
Reading symbols from /bin/ls...(no debugging symbols found)...done.
(gdb)
```

**Comment by zachriggle** [comment]
This was a Python3-ism, not related to Vivid.  Fixed in 90726f7 / ca6d30f.
